### ISSUE TITLE
`requestStorageAccess` and `hasStorageAccess` must not enable discrimination against the users who have rejected to provide unpartitioned access

### ISSUE THREAD

**Issue by KOLANICH** [privacycg/storage-access#103]

**Comment by eligrey** [comment]
Your request does not seem possible given the nature of these functions.

**Comment by KOLANICH** [comment]
1. `hasStorageAccess` can be just eliminated while it's not too late. As an alternative solution, it should always return `Promise.resolve(true)`.
2. `requestStorageAccess()` should always fullfill no matter if the user has aggreed or rejected.

Of course site owners can implement the check on their side by creating unique identifiers and cross-origin smuggling them and communicating the info on backend side and checking whether the identifiers match the cookies. But I currently believe that at least this way the mere fact of presence of this API wouldn't facilitate discrimination: the routine described doesn't depend on the API presence.

**Comment by johannhof** [comment]
I understand where you're coming from but this issue assumes default partitioning of 3rd party cookies, which is currently only done in Firefox, and they have indicated that they would prefer to align with Safari (and future Chrome) and start blocking by default. It's trivial to detect whether 3rd party cookies are blocked or not.

`hasStorageAccess` and rejecting `requestStorageAccess` provide utility to web developers that we shouldn't throw away when there's nothing to gain. Note that the information provided to web developers by these functions is already quite sparse as mentioned in #37 and in my opinion that's enough, too. If a party has enough motivation to discriminate against clients which are blocking 3PC there are, as you mention, only slightly more complicated ways to do so still (i.e. it doesn't have to be a unique identifier, just a cookie that the site knows will not be set in an embedded context).

**Comment by johannhof** [comment]
I'm closing this, as we're quite seriously aware of this concern as evidenced in #60. There's work on #120 and I don't think we'll go any stronger than that.
