### ISSUE TITLE
Is this an error in the spec: Chromium using `storage-access-api` and not `request-storage-access` for permissions policy

### ISSUE THREAD

**Issue by summercms** [privacycg/storage-access#104]
The spec say's:

> The Storage Access API defines a [policy-controlled feature](https://w3c.github.io/webappsec-permissions-policy/#policy-controlled-feature) identified by the string "request-storage-access". Its [default allowlist](https://w3c.github.io/webappsec-permissions-policy/#default-allowlist) is "*".

Link: https://privacycg.github.io/storage-access/#permissions-policy-integration

Yet in the Chromium source code says: the policy name is: `storage-access-api` and not `request-storage-access` ?

```json5
{
      name: "StorageAccessAPI",
      feature_default: "EnableForAll",
      permissions_policy_name: "storage-access-api",
      depends_on: ["StorageAccessAPI"],
},
```

Link: https://source.chromium.org/chromium/chromium/src/+/main:third_party/blink/renderer/core/permissions_policy/permissions_policy_features.json5

Just wondering if there is an issue in the spec or not? Or is the code in Chromium wrong?

cc @johannhof As one of the editors and on the Chrome team.

**Comment by johannhof** [comment]
Thanks for noticing this and sorry for the delay! Given that neither Safari nor Firefox have shipped this name I think the spec should align with the only existing implementation. There were some concerns with the `storage-access` name in https://github.com/privacycg/storage-access/issues/12 but the `-api` part might help with that. I can make a PR for updating this in the spec.

**Comment by johannhof** [comment]
To follow up here, we'll rename this in Chromium to "storage-access" and I also made that change on the spec.

**Comment by cetinsert** [comment]
@johannhof – when is the Storage Access API shipping in Chrome?

**Comment by johannhof** [comment]
Hi @cetinsert, I don't have a definitive date yet but we just sent out an intent to prototype for [requestStorageAccessForSite](https://github.com/mreichhoff/requestStorageAccessForSite) in addition to the existing I2P from Microsoft Edge. It's easiest to follow the [Chromestatus entries](https://chromestatus.com/features#storageaccess) for both efforts for timely updates.

**Comment by rian1223416** [comment]
https://github.com/privacycg/storage-access/issues/104
