### ISSUE TITLE
I'm somewhat concerned about giving websites the ability to revoke permissions. It seems this could lead to a confusing user experience where the user ends up seeing the same dialog over and over.

### ISSUE THREAD

**Issue by Trener691** [privacycg/storage-access#128]
I'm somewhat concerned about giving websites the ability to revoke permissions. It seems this could lead to a confusing user experience where the user ends up seeing the same dialog over and over.

_Originally posted by @annevk in https://github.com/privacycg/storage-access/issues/127#issuecomment-1286685549_

**Comment by johannhof** [comment]
I assume this was filed by mistake.

**Comment by miketaylr** [comment]
(this looks like bot activity, based on the profile)
