### ISSUE TITLE
Adapt changes to navigation to session history rewrite

### ISSUE THREAD

**Issue by johannhof** [privacycg/storage-access#137]
We have some [new build errors](https://github.com/privacycg/storage-access/actions/runs/3418031599/jobs/5689838110):

```
LINE ~275: No 'dfn' refs found for 'current entry'.
[=current entry=]
```

in https://privacycg.github.io/storage-access/#navigation

I suspect that this comes from https://github.com/whatwg/html/pull/6315. I asked @domenic about an easy migration path for this text but it seems like the solution might entail a little more work, so here's two thoughts:

- I think we should unbreak the build in the meantime, with https://github.com/privacycg/storage-access/pull/136
- I'm not sure how much of this will stick around with the upcoming Permissions integration (#121), so I'm a bit hesitant to spend the time on fixing this now and having to rewrite/delete that portion later.

@annevk thoughts?

**Comment by annevk** [comment]
If we remove the warning check we'll likely end up introducing quite a few new problems. I would prefer we add an issue marker and remove the broken references (keeping the words, but no longer linking them) if we want a temporary solution.

**Comment by johannhof** [comment]
Ok that seems like a better solution to me as well, then. I'll comment on the PR.

**Comment by johannhof** [comment]
I think this was solved with #121 but please correct me if I'm wrong @cfredric

**Comment by cfredric** [comment]
I think you meant #141, but I agree, #136 fixed the build by unlinking "current entry", and as of #141 the spec no longer references the "current entry" directly, so this seems fixed.

**Comment by johannhof** [comment]
Oh, yes, I meant #141, sorry.
