### ISSUE TITLE
hasStorageAccess() deals with promises in parallel

### ISSUE THREAD

**Issue by domfarolino** [privacycg/storage-access#151]
While in parallel, the [`hasStorageAccess()`](https://privacycg.github.io/storage-access/#dom-document-hasstorageaccess) algorithm creates a promise and fulfills it in-parallel, which [is an invalid usage](https://html.spec.whatwg.org/multipage/webappapis.html#event-loop-for-spec-authors:~:text=Promises%2C%20as%20observable%20JavaScript%20objects%2C%20are%20never%20created%20and%20manipulated%20during%20the%20in%20parallel) of the Promise API.

More generally, I don't really understand the flow of that algorithm. The method itself returns a promise and then right when it goes in parallel it creates _another_ promise which becomes the resolved value of the outer promise? It seems like we should just pass in the first promise (that was properly created on the main thread) into the https://privacycg.github.io/storage-access/#determine-the-storage-access-policy algorithm, which would then resolve/reject it accordingly.

**Comment by cfredric** [comment]
Worth noting that both of those issues will be fixed in my PR (#141).

**Comment by annevk** [comment]
This has indeed been resolved, although we might move back to using in parallel in #174 (but without this issue).
