### ISSUE TITLE
Editorial: Consider removing implementation-defined steps because we have requesting permission to use

### ISSUE THREAD

**Issue by johannhof** [privacycg/storage-access#156]
[Requesting permission to use](https://w3c.github.io/permissions/#dfn-request-permission-to-use) should allow UAs to make implementation-defined decisions around whether or not prompts are shown. We could consider removing the implementation defined steps in determining the storage access policy and just adding some more clarification in the Permissions API.

This might make it harder to understand that there are implementation defined steps involved, so I'm not sure we should do it.

cc @annevk

**Comment by bvandersloot-mozilla** [comment]
I think it is fine, so long as we throw a Note in that makes it clear that the Permissions API contains implementation variation.
