### ISSUE TITLE
Update README with Chrome status

### ISSUE THREAD

**Issue by moos** [privacycg/storage-access#18]
Chrome work on feature is in progress.  Status: https://www.chromestatus.com/feature/5612590694662144

**Comment by johnwilander** [comment]
Thanks for filing! I do believe the README is correct. It’s Microsoft who’s implementing the Storage Access API in Chromium and they are listed as such. If you have seen a public positive signal from Chrome, I’m very happy to add them.

**Comment by moos** [comment]
I believe the link above is _Chrome's_ official feature status.  Plus there is no indication that [the work being done](https://bugs.chromium.org/p/chromium/issues/detail?id=989663) on Chromium is exclusive to Microsoft.

**Comment by erik-anderson** [comment]
The Storage Access API implementation work in Chromium is being done by the Edge team, with code review and design feedback from the Chrome team. I don't believe the Chrome team has given a public signal about if they plan to ship with the feature enabled in Chrome or not; different Chromium embedders can and do make independent decisions about what features are enabled in their browsers. I believe "Chrome: No public signal" is accurate at this time.

**Comment by johnwilander** [comment]
Thanks for the clarification, Erik! Closing.
