### ISSUE TITLE
Option to specify extended lifetime

### ISSUE THREAD

**Issue by fastest963** [privacycg/storage-access#20]
Brought up on the call but thought I'd make an issue to discuss further.

Since Safari announced limiting all storage data to 7 days there have been multiple posts from developers claiming this would affect their offline-only web app. I'm curious if we'd be interested in adding a parameter to the `requestStorageAccess` to specify a lifetime. The browser would choose to honor it or not and present it to the user if necessary. This could be called by a first-party if the offline-only app expected the user to need to have their data persist longer than the default expiration imposed by the browser.

Alternatively, it might be better to instead defer this to `navigator.storage.persist()` as defined in https://storage.spec.whatwg.org/. Since Safari doesn't implement that at the moment I thought I'd bring it up here in case they believe it's better to be handled by this spec instead.

**Comment by johnwilander** [comment]
Thanks for filing. I still feel this would create a whole new purpose for the Storage Access API. Someone brought up that [Storage Persistence Permission](https://storage.spec.whatwg.org/#persistence) may the right thing to look at.

**Comment by fastest963** [comment]
Yeah, I brought that up, but it's not supported in Safari at the moment so that's why I brought it up here for consideration with this API instead of Safari has a preference either way.

**Comment by hober** [comment]
I'm going to close this, since the aforementioned features of the Storage Standard seem to address the use case. Please let me know if I've missed something.
