### ISSUE TITLE
Define 'expression of permission' when user response is undefined

### ISSUE THREAD

**Issue by Brandr0id** [privacycg/storage-access#26]
In **3.1.1. User Agent storage access policies** an 'expression of permission' is defined to represent the result of prompting the user. The current state of true == explicit allow and false == explicit deny makes sense. I don't think we necessarily would want to set the 'was-expressly-denied-storage-access-flag' if they didn't expressly deny access.

However there exists the case where the prompt may be dismissed without providing a response. I believe it's best to treat these as a deny and reject the promise rather than leaving it unresolved but without the permanent effect so a subsequent prompt "may" be made if the UA allowed it. Can we call out this scenario in the spec where the **expression of permission** isn't explicitly true/false but the question has been resolved in an undefined manner?

**Comment by hober** [comment]
I think I've addressed this in #27. Please take a look.
