### ISSUE TITLE
Share a task queue with the Permissions API?

### ISSUE THREAD

**Issue by hober** [privacycg/storage-access#34]
Currently we define our own `storage access request queue`. Could we use the `permission task source` instead?

See also #12, #32, and w3c/permissions#206.

**Comment by Brandr0id** [comment]
Seems reasonable to me and aligns with feedback I received from Chromium area owners when implementing the prompt logic. This also has some side effects that the APIs prompt also receives similar protections as other permissions w.r.t. frequent prompts and dismissals/rejections for given origin pairs on top of any explicit flags/logic we define here.

**Comment by annevk** [comment]
I don't think those protections are defined and given that the task source is per event loop you probably need something else to define those kind of details. (No objections to aligning these though.)
