### ISSUE TITLE
Opt-out persistance

### ISSUE THREAD

**Issue by jdwieland8282** [privacycg/storage-access#52]
**UseCase:** As a user I want to opt-out of tracking by sniffy.com (sniffy.com has tracking pixels on many of the sites I visit) so that I can browser content on my favorite sites w/o sniffy.com being able to track me. 

In this use case, persisting the users opt-out preferences across the domains he or she visits is a requirement (today that is done by setting a 3rd party cookie that sniffy can read, for example optout=true).  W/o the ability to set a 3rd party cookie, sniffy needs a way to know what this users opt-out preferences are.  We've explored the storage access api as an option and were curious to know whether the members of this group have consider it valid, or if there is an option more palatable?

**Comment by johnwilander** [comment]
I believe this has been brought up in other issues. The Storage Access API does not apply different rules depending on the purpose of the storage access request. It doesn't know the purpose.

**Comment by jdwieland8282** [comment]
thanks @johnwilander I'll poke around and see if I can find some of the other issues that reference this use case.
