### ISSUE TITLE
Add "Explicitly grant permission to sites globally" to considered alternatives

### ISSUE THREAD

**Issue by kushal** [privacycg/storage-access#9]
Just for completeness, it might be nice to lay out the reasoning here. To the extent that the concern is abuse or overuse, one could imagine explicit permission grants + in-browser reminders of when the permission is accessed working similarly to various mobile OS permissions in terms of striking a balance between usability and safety.

**Comment by johnwilander** [comment]
I'll add this the spec in some form.

**Comment by johannhof** [comment]
I think this issue is stale and none of the current editors still has enough context and time for this. Closing for now, feel free to re-open if you feel that it's really important.
